### ISSUE TITLE
"TypeError: Object #<Object> has no method 'parse'"

### ISSUE THREAD

**Issue by cleercode** [manifoldjs/ManifoldJS#116]
Any ideas? Clean install from npm just now.

```
$ manifoldjs http://google.com
WARNING: No manifest found. A new manifest will be created.
WARNING: Manifest validation  (Windows) - A small square logo of any of the following sizes is required for Windows: 24x24, 30x30, 42x42, 54x54[icons]
WARNING: Manifest validation  (Windows) - A splash screen logo of any of the following sizes is required for Windows: 620x300, 868x420, 1116x540[icons]
WARNING: Manifest validation  (Windows) - A square logo of any of the following sizes is required for Windows: 120x120, 150x150, 210x210, 270x270[icons]
WARNING: Manifest validation  (Windows) - A store logo of any of the following sizes is required for Windows: size 50x50, 70x70, 90x90[icons]
WARNING: Manifest validation  (Windows) - An app icon of any of the following sizes is required for Windows Phone: 44x44, 62x62, 106x106[icons]
WARNING: Manifest validation  (Windows) - A medium tile logo of any of the following sizes is required for Windows Phone: 150x150, 210x210, 360x360[icons]
WARNING: Manifest validation  (Windows) - A small tile logo of any of the following sizes is required for Windows Phone: 71x71, 99x99, 170x170[icons]
WARNING: Manifest validation  (Windows) - A store logo of any of the following sizes is required for Windows Phone: 50x50, 70x70, 120x120[icons]
WARNING: Manifest validation  (Android) - Launcher icons of the following sizes are required: 48x48, 72x72, 96x96, 144x144, 192x192, 512x512[icons]
WARNING: Manifest validation  (iOS) - An app icon of the following sizes is required: 76x76, 120x120, 152x152 and 180x180[icons]
WARNING: Manifest validation  (iOS) - An 1024x1024 app icon for the App Store is required[icons]
WARNING: Manifest validation  (iOS) - A launch image of the following sizes is required: 750x1334, 1334x750, 1242x2208, 2208x1242, 640x1136, 640x960, 1536x2048, 2048x1536, 768x1024 and 1024x768[icons]
SUGGESTION: Manifest validation  (Chrome) - A 48x48 icon should be provided for the extensions management page (chrome://extensions)[icons]
SUGGESTION: Manifest validation  (Chrome) - It is recommended to have a 16x16 favicon[icons]
WARNING: Manifest validation  (Chrome) - A 128x128 icon is required for the installation process and the Chrome Web Store[icons]
SUGGESTION: Manifest validation  (Firefox) - Firefox 2.0 onwards, an 512x512 icon is recommended for Firefox Marketplace and devices[icons]
WARNING: Manifest validation  (Firefox) - A 128x128 icon is required for the Firefox Marketplace and the devices[icons]
SUGGESTION: Manifest validation  (Firefox) - It is recommended to provide icon sizes for multiple platforms, including: 16x16, 32x32, 48x48, 64x64, 90x90, 128x128 and 256x256[icons]
SUGGESTION: Manifest validation  (All Platforms) - It is recommended to specify a set of access rules that represent the navigation scope of the application[mjs_access_whitelist]

/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:155
                throw e;
                      ^
TypeError: Object #<Object> has no method 'parse'
    at mkdirp (/usr/local/lib/node_modules/manifoldjs/lib/projectBuilder.js:23:23)
    at /usr/local/lib/node_modules/manifoldjs/lib/projectBuilder.js:645:5
    at /usr/local/lib/node_modules/manifoldjs/lib/manifestTools.js:233:9
    at _fulfilled (/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:415:13)
```

**Comment by f2bo** [comment]
Hi @cleercode,

Yes. This happens when you are using an older release of Node.js that doesn't support some of the features required by the current version of ManifoldJS. You should be fine if you upgrade to 0.12.x.

We'll be more specific about the version required in future releases.

Also, see https://github.com/manifoldjs/ManifoldJS/issues/97.
