### ISSUE TITLE
builder chokes on icon creation

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#262]
Two sites:
https://www.duolingo.com/
https://www.ted.com/ 

both seem to choke up on generating the icons.
C:\Users\jeffburt\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\xanifoldjs-lib\lib\manifestTools\manifestCreator\scrapers\icons.js:111
        var size = $icon.prop('tagName');
                         ^

TypeError: $icon.prop is not a function
    at C:\Users\jeffburt\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\xanifoldjs-lib\lib\manifestTools\manifestCreator\scrapers\icons.js:111:26
    at Array.map (native)
    at Request._callback (C:\Users\jeffburt\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\xanifoldjs-lib\lib\manifestTools\manifestCreator\scrapers\icons.js:108:8)
    at Request.self.callback (C:\Users\jeffburt\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\xanifoldjs-lib\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\jeffburt\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\xanifoldjs-lib\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\jeffburt\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\xanifoldjs-lib\node_modules\request\request.js:1001:12)

**Comment by boyofgreen** [comment]
@kenchris  found out thiat this one is broken too http://politiken.dk/  and http://pol.dk    @michael-hawker  please add it to your list.  If this turns out to be a different issue, separate it into a new issue

**Comment by msrodri** [comment]
Apparently, the error thrown by the https://www.duolingo.com/ site seems to be different. I created a new issue for it #271

**Comment by rnrneverdies** [comment]
Fixed, will be available in the next major release.
