### ISSUE TITLE
builder fails when detecting .ico images when the image URL contains querystrings

### ISSUE THREAD

**Issue by msrodri** [manifoldjs/ManifoldJS#271]
Can be reproduced with https://www.duolingo.com/

The main page defines the following image:

`<link href="/images/favicon.ico?v=3" rel="shortcut icon" type="image/x-icon" />`

The builder does not properly detect the "ico" image type, and as a fallback uses a different image parser that fails as follows:

```
d:\Projects\manifoldjs\ManifoldJS\node_modules\manifoldjs-lib\node_modules\image-size\lib\index.js:34
  throw new TypeError('unsupported file type: ' + type + ' (file: ' + filepath
        ^
TypeError: unsupported file type: undefined (file: undefined)
    at lookup (d:\Projects\manifoldjs\ManifoldJS\node_modules\manifoldjs-lib\node_modules\image-size\lib\index.js:34:9)
    at module.exports (d:\Projects\manifoldjs\ManifoldJS\node_modules\manifoldjs-lib\node_modules\image-size\lib\index.js:74:12)
    at Request._callback (d:\Projects\manifoldjs\ManifoldJS\node_modules\manifoldjs-lib\lib\manifestTools\manifestCreator\scrapers\icons.js:36:24)
    at Request.init.self.callback (d:\Projects\manifoldjs\ManifoldJS\node_modules\manifoldjs-lib\node_modules\request\request.js:188:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (d:\Projects\manifoldjs\ManifoldJS\node_modules\manifoldjs-lib\node_modules\request\request.js:1171:10)
    at Request.emit (events.js:107:17)
    at IncomingMessage.<anonymous> (d:\Projects\manifoldjs\ManifoldJS\node_modules\manifoldjs-lib\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:129:20)
```

**Comment by rnrneverdies** [comment]
Fixed, will be available in the next major release.
