### ISSUE TITLE
Some sites are returning error from `getManifestFromSite`

### ISSUE THREAD

**Issue by ryanbillingsley** [manifoldjs/ManifoldJS#5]
If I try and run my site `www.tacosfeedthebear.com` through `getManifestFromSite` I would expect a warning that no manifest exists and that a new one will be created, but instead I am seeing:

```
Error: Failed to retrieve manifest from site.
```

Stacktrace:

```
Error: Failed to retrieve manifest from site.
    at Request._callback (/Users/ryanbillingsley/Dev/manifold-api/node_modules/manifoldjs/lib/manifestTools.js:105:23)
    at Request.self.callback (/Users/ryanbillingsley/Dev/manifold-api/node_modules/manifoldjs/node_modules/request/request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/ryanbillingsley/Dev/manifold-api/node_modules/manifoldjs/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/ryanbillingsley/Dev/manifold-api/node_modules/manifoldjs/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by msrodri** [comment]
The issue is that ```getManifestFromSite``` method is sending a raw GET request (no headers) to retrieve the content of the home page and look for a manifest; however, the ```www.tacosfeedthebear.com``` is returning a ```403 (forbidden)``` to that type of requests -presumably as a defense mechanism against attacks.

We get a ```200 (OK)``` response when we send a user agent, example:
```
User-Agent: 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36'
```
In any case, we'll analyze the best approach to address those scenarios.
