### ISSUE TITLE
Failing to build on Azure

### ISSUE THREAD

**Issue by ryanbillingsley** [manifoldjs/ManifoldJS#9]
`ERROR: Failed to add the Hosted Web App plugin to the Cordova project.`

Seeing this when attempting to the build the projects on Azure.

Full stack trace:

```
ERROR: Failed to add the Hosted Web App plugin to the Cordova project.
WARNING: The Cordova project could not be created successfully.
POST /manifests/9cc50462-8c52-4406-a50a-6a226352cfad/build 500 16058.088 ms - 22
Error: One or more errors occurred when generating the application.
    at D:\home\site\wwwroot\node_modules\manifoldjs\lib\projectBuilder.js:55:21
    at Array.forEach (native)
    at D:\home\site\wwwroot\node_modules\manifoldjs\lib\projectBuilder.js:51:17
    at _fulfilled (D:\home\site\wwwroot\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (D:\home\site\wwwroot\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (D:\home\site\wwwroot\node_modules\q\q.js:756:13)
    at D:\home\site\wwwroot\node_modules\q\q.js:564:44
    at flush (D:\home\site\wwwroot\node_modules\q\q.js:110:17)
    at process._tickCallback (node.js:419:13)
```

**Comment by nbellocam** [comment]
Hi Ryan,

The issue is related to the way ManifoldJS is referencing the ManifoldCordova plugin (which is a component required for building the Cordova applications). Since the plugin is not yet published in the Cordova's plugin registry, the tool is pointing the GitHub repository instead of a plugin id. This approach works fine when the git command is globally available, which is not the case for Azure Websites. 

In order to workaround this issue, ManifoldJS was updated to install and reference the Cordova plugin locally.

**Comment by ryanbillingsley** [comment]
So I added `loglevel` and am using the newer version of the library and this is my output

```
Building the project { content: 
   { start_url: 'http://www.bamideas.com',
     short_name: 'WwwBamideasCom' },
  format: 'w3c',
  id: '0b0dc4a7-2883-4310-b89a-1966b4993163' } D:\home\site\wwwroot\tmp\0b0dc4a7-2883-4310-b89a-1966b4993163 [ 'windows', 'android', 'ios', 'chrome', 'firefox' ] false
```
This is my logging showing the manifest we will be using as well as the platforms.

```
Generating the Chrome application...
Generating the Firefox application...
Generating the Cordova application...
Creating the Cordova project...
    D:\home\site\wwwroot\node_modules\manifoldjs\node_modules\cordova\bin\cordova create cordova com.bamideas.www WwwBamideasCom
Downloading Chrome icons...
Copying the Chrome manifest to the app folder...
Copying the Firefox manifest to the app folder...
Creating a new cordova project with name "WwwBamideasCom" and id "com.bamideas.www" at location "D:\home\site\wwwroot\tmp\0b0dc4a7-2883-4310-b89a-1966b4993163\WwwBamideasCom\cordova"
Copying the W3C manifest to the app folder...
Creating a new cordova project with name "WwwBamideasCom" and id "com.bamideas.www" at location "D:\home\site\wwwroot\tmp\0b0dc4a7-2883-4310-b89a-1966b4993163\WwwBamideasCom\cordova"
Adding the Hosted Web App plugin to the Cordova project...
    D:\home\site\wwwroot\node_modules\manifoldjs\node_modules\cordova\bin\cordova plugin add D:\home\site\wwwroot\node_modules\manifoldjs\node_modules\ManifoldCordova

Adding Cordova platform: windows...
    D:\home\site\wwwroot\node_modules\manifoldjs\node_modules\cordova\bin\cordova platform add windows
Adding Cordova platform: android...
    D:\home\site\wwwroot\node_modules\manifoldjs\node_modules\cordova\bin\cordova platform add android
Adding Cordova platform: ios...
    D:\home\site\wwwroot\node_modules\manifoldjs\node_modules\cordova\bin\cordova platform add ios
WARNING: Applications for platform ios can not be built on this OS - win32.
Adding ios project...
iOS project created with cordova-ios@3.8.0
Updating Cordova configuration from W3C manifest...
Installing "com.manifoldjs.hostedwebapp" for ios
WARNING: Failed to add ios platform.
{ [Error: Command failed: ] killed: false, code: 1, signal: null }
Adding windows project...
Creating Cordova Windows Project:
	App Name  : WwwBamideasCom
	Namespace : com.bamideas.www
	Path      : D:\home\site\wwwroot\tmp\0b0dc4a7-2883-4310-b89a-1966b4993163\WwwBamideasCom\cordova\platforms\windows
Copying template to D:\home\site\wwwroot\tmp\0b0dc4a7-2883-4310-b89a-1966b4993163\WwwBamideasCom\cordova\platforms\windows
Updating Cordova configuration from W3C manifest...
Applying windows fix...
Installing "com.manifoldjs.hostedwebapp" for windows
Fetching plugin "org.apache.cordova.network-information" via plugin registry
Installing "org.apache.cordova.network-information" for windows
Creating shortcut for platform: windows...
Adding windows project...
Creating Cordova Windows Project:
	App Name  : WwwBamideasCom
	Namespace : com.bamideas.www
	Path      : D:\home\site\wwwroot\tmp\0b0dc4a7-2883-4310-b89a-1966b4993163\WwwBamideasCom\cordova\platforms\windows
Copying template to D:\home\site\wwwroot\tmp\0b0dc4a7-2883-4310-b89a-1966b4993163\WwwBamideasCom\cordova\platforms\windows
Updating Cordova configuration from W3C manifest...
Applying windows fix...
Installing "com.manifoldjs.hostedwebapp" for windows
Fetching plugin "org.apache.cordova.network-information" via plugin registry
Installing "org.apache.cordova.network-information" for windows
WARNING: Failed to create shortcut for platform: windows.
{ [Error: EPERM, symlink 'D:\home\site\wwwroot\tmp\0b0dc4a7-2883-4310-b89a-1966b4993163\WwwBamideasCom\cordova\platforms\windows']
  errno: 50,
  code: 'EPERM',
  path: 'D:\\home\\site\\wwwroot\\tmp\\0b0dc4a7-2883-4310-b89a-1966b4993163\\WwwBamideasCom\\cordova\\platforms\\windows' }
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms\android
	Package: com.bamideas.www
	Name: WwwBamideasCom
	Android target: android-21
Copying template files...
Project successfully created.
Updating Cordova configuration from W3C manifest...
Installing "com.manifoldjs.hostedwebapp" for android
Fetching plugin "org.apache.cordova.network-information" via plugin registry
rm: could not remove directory (code ENOTEMPTY): D:\home\site\wwwroot\tmp\0b0dc4a7-2883-4310-b89a-1966b4993163\WwwBamideasCom\cordova\plugins\org.apache.cordova.network-information

skipping existing file: NetworkManager.java
skipping existing file: index.js
skipping existing file: NetworkProxy.js
skipping existing file: NetworkProxy.js
skipping existing file: CDVConnection.h
skipping existing file: CDVConnection.m
skipping existing file: CDVReachability.h
skipping existing file: CDVReachability.m
skipping existing file: NetworkProxy.js
skipping existing file: network_information.cpp
skipping existing file: network_information.h
skipping existing file: NetworkInfoProxy.js
skipping existing file: NetworkStatus.cs
skipping existing file: plugin.xml
skipping existing file: tests.js
skipping existing file: Connection.js
skipping existing file: network.js
Installing "org.apache.cordova.network-information" for android
Creating shortcut for platform: android...
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms\android
	Package: com.bamideas.www
	Name: WwwBamideasCom
	Android target: android-21
Copying template files...
Project successfully created.
Updating Cordova configuration from W3C manifest...
Installing "com.manifoldjs.hostedwebapp" for android
Fetching plugin "org.apache.cordova.network-information" via plugin registry
rm: could not remove directory (code ENOTEMPTY): D:\home\site\wwwroot\tmp\0b0dc4a7-2883-4310-b89a-1966b4993163\WwwBamideasCom\cordova\plugins\org.apache.cordova.network-information

skipping existing file: NetworkManager.java
skipping existing file: index.js
skipping existing file: NetworkProxy.js
skipping existing file: NetworkProxy.js
skipping existing file: CDVConnection.h
skipping existing file: CDVConnection.m
skipping existing file: CDVReachability.h
skipping existing file: CDVReachability.m
skipping existing file: NetworkProxy.js
skipping existing file: network_information.cpp
skipping existing file: network_information.h
skipping existing file: NetworkInfoProxy.js
skipping existing file: NetworkStatus.cs
skipping existing file: plugin.xml
skipping existing file: tests.js
skipping existing file: Connection.js
skipping existing file: network.js
Installing "org.apache.cordova.network-information" for android
WARNING: Failed to create shortcut for platform: android.
{ [Error: EPERM, symlink 'D:\home\site\wwwroot\tmp\0b0dc4a7-2883-4310-b89a-1966b4993163\WwwBamideasCom\cordova\platforms\android']
  errno: 50,
  code: 'EPERM',
  path: 'D:\\home\\site\\wwwroot\\tmp\\0b0dc4a7-2883-4310-b89a-1966b4993163\\WwwBamideasCom\\cordova\\platforms\\android' }
[0mPOST /manifests/0b0dc4a7-2883-4310-b89a-1966b4993163/build [31m500 [0m55888.779 ms - 22[0m
WARNING: One or more tasks failed while generating the Cordova application.
Error: One or more errors occurred when generating the application.
    at D:\home\site\wwwroot\node_modules\manifoldjs\lib\projectBuilder.js:71:21
    at Array.forEach (native)
    at D:\home\site\wwwroot\node_modules\manifoldjs\lib\projectBuilder.js:67:17
    at _fulfilled (D:\home\site\wwwroot\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (D:\home\site\wwwroot\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (D:\home\site\wwwroot\node_modules\q\q.js:756:13)
    at D:\home\site\wwwroot\node_modules\q\q.js:564:44
    at flush (D:\home\site\wwwroot\node_modules\q\q.js:110:17)
    at process._tickCallback (node.js:419:13)
```

The process is failing and I can't get a project to build.  The interesting thing is that this is working locally.  Any ideas?
