### ISSUE TITLE
Crash when trying to package https://kenchris.github.io

### ISSUE THREAD

**Issue by kenchris** [manifoldjs/ManifoldJS#97]
$ manifoldjs https://kenchris.github.com -p android -c 
SUGGESTION: Manifest validation  (All Platforms) - It is recommended to specify a set of access rules that represent the navigation scope of the application[mjs_access_whitelist]

/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:155
                throw e;
                      ^
TypeError: Object #<Object> has no method 'parse'
    at mkdirp (/usr/local/lib/node_modules/manifoldjs/lib/projectBuilder.js:23:23)
    at /usr/local/lib/node_modules/manifoldjs/lib/projectBuilder.js:645:5
    at /usr/local/lib/node_modules/manifoldjs/lib/manifestTools.js:233:9
    at _fulfilled (/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/manifoldjs/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:415:13)

**Comment by f2bo** [comment]
This can be resolved by updating Node.js. The latest release of ManifoldJS makes use of some features that were not available in earlier versions of Node. 

We'll be more specific about the version of Node required in future releases.

**Comment by kenchris** [comment]
You could catch the error and ask people to update node... or check the node version when invoking manifestjs

**Comment by boyofgreen** [comment]
Hi Kenneth,   You are right, we will put a check in place.

**Comment by msrodri** [comment]
We updated package.json to specify the min version of node required for the tool to work. The manifoldjs package will fail to install if version of node older than 0.12.0 is installed.
